version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test-currency-rate
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data